### ISSUE TITLE
TCP/UDP support

### ISSUE THREAD

**Issue by HelderFSFerreira** [tomMoulard/fail2ban#22]
Hello,

Are TCP or UDP entrypoints supported?

Thank you!

**Comment by tomMoulard** [comment]
Hi,

We did not test with UDP, just TCP. But since we just manage IP addresses, I Think both TCP and UDP are supported by traefik thus by the plugin.

Regards,

Tom

**Comment by HelderFSFerreira** [comment]
Ok thank you.
My goal is not use it in front of a git+ssh server.

Thanks!
