### ISSUE TITLE
Configuring rules for response codes

### ISSUE THREAD

**Issue by marrold** [tomMoulard/fail2ban#46]
Hi, 

Thanks for creating this project, it looks very useful. 

Is it possible to add rules for response codes instead of URL paths? E.G for 401 / 403 response from upstream server?

Thanks

**Comment by tomMoulard** [comment]
Hello @marrold,

Thanks for your interest in this Traefik plugin !

Feel free to open a PR to add this feature to the project.

**Comment by marrold** [comment]
Okay, thanks

**Comment by tomMoulard** [comment]
Please, keep the issue open until this feature is implemented.

**Comment by tomMoulard** [comment]
Closing as #108 is merged, thanks!
