### ISSUE TITLE
Dashboard preview/admin console of current state

### ISSUE THREAD

**Issue by aqos156** [tomMoulard/fail2ban#57]
## Proposal
Do not know whether it is possible with plugins, but add a dashboard preview of all banned IPs with the ability to unban, possibly whitelist/blacklist them (this would require a separate db file probably), ...

**Comment by tomMoulard** [comment]
Hello @aqos156,
I don't think it is possible to have a dashboard for plugins in traefik. This may need a feature request on traefik itself.
