### ISSUE TITLE
Trademark Infringement

### ISSUE THREAD

**Issue by Jake-E** [tomMoulard/fail2ban#94]
Good afternoon,

The asset used as the logo for this project on the Traefik community page, hosted [here](https://github.com/tomMoulard/fail2ban/blob/main/.assets/f2b.png) is a registered UK trademark with registration number [UK00003584429](https://trademarks.ipo.gov.uk/ipo-tmcase/page/Results/1/UK00003584429).

Please remove our trademarked asset from this project.

**Comment by tomMoulard** [comment]
Woaw my bad, I will do that ASAP
